
package techassist.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TechAssistServerService", targetNamespace = "http://techassist/", wsdlLocation = "http://localhost:8888/TechAssist?wsdl")
public class TechAssistServerService
    extends Service
{

    private final static URL TECHASSISTSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException TECHASSISTSERVERSERVICE_EXCEPTION;
    private final static QName TECHASSISTSERVERSERVICE_QNAME = new QName("http://techassist/", "TechAssistServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/TechAssist?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TECHASSISTSERVERSERVICE_WSDL_LOCATION = url;
        TECHASSISTSERVERSERVICE_EXCEPTION = e;
    }

    public TechAssistServerService() {
        super(__getWsdlLocation(), TECHASSISTSERVERSERVICE_QNAME);
    }

    public TechAssistServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TECHASSISTSERVERSERVICE_QNAME, features);
    }

    public TechAssistServerService(URL wsdlLocation) {
        super(wsdlLocation, TECHASSISTSERVERSERVICE_QNAME);
    }

    public TechAssistServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TECHASSISTSERVERSERVICE_QNAME, features);
    }

    public TechAssistServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TechAssistServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TechAssistServer
     */
    @WebEndpoint(name = "TechAssistServerPort")
    public TechAssistServer getTechAssistServerPort() {
        return super.getPort(new QName("http://techassist/", "TechAssistServerPort"), TechAssistServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TechAssistServer
     */
    @WebEndpoint(name = "TechAssistServerPort")
    public TechAssistServer getTechAssistServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://techassist/", "TechAssistServerPort"), TechAssistServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TECHASSISTSERVERSERVICE_EXCEPTION!= null) {
            throw TECHASSISTSERVERSERVICE_EXCEPTION;
        }
        return TECHASSISTSERVERSERVICE_WSDL_LOCATION;
    }

}
