
package techassist.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TechAssistServer", targetNamespace = "http://techassist/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TechAssistServer {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://techassist/", className = "techassist.service.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://techassist/", className = "techassist.service.GetStatusResponse")
    @Action(input = "http://techassist/TechAssistServer/getStatusRequest", output = "http://techassist/TechAssistServer/getStatusResponse")
    public String getStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.util.List<techassist.service.Request>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRequests", targetNamespace = "http://techassist/", className = "techassist.service.GetRequests")
    @ResponseWrapper(localName = "getRequestsResponse", targetNamespace = "http://techassist/", className = "techassist.service.GetRequestsResponse")
    @Action(input = "http://techassist/TechAssistServer/getRequestsRequest", output = "http://techassist/TechAssistServer/getRequestsResponse")
    public List<Request> getRequests();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "startRequest", targetNamespace = "http://techassist/", className = "techassist.service.StartRequest")
    @ResponseWrapper(localName = "startRequestResponse", targetNamespace = "http://techassist/", className = "techassist.service.StartRequestResponse")
    @Action(input = "http://techassist/TechAssistServer/startRequestRequest", output = "http://techassist/TechAssistServer/startRequestResponse")
    public void startRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createRequest", targetNamespace = "http://techassist/", className = "techassist.service.CreateRequest")
    @ResponseWrapper(localName = "createRequestResponse", targetNamespace = "http://techassist/", className = "techassist.service.CreateRequestResponse")
    @Action(input = "http://techassist/TechAssistServer/createRequestRequest", output = "http://techassist/TechAssistServer/createRequestResponse")
    public int createRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "finishRequest", targetNamespace = "http://techassist/", className = "techassist.service.FinishRequest")
    @ResponseWrapper(localName = "finishRequestResponse", targetNamespace = "http://techassist/", className = "techassist.service.FinishRequestResponse")
    @Action(input = "http://techassist/TechAssistServer/finishRequestRequest", output = "http://techassist/TechAssistServer/finishRequestResponse")
    public void finishRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "denyRequest", targetNamespace = "http://techassist/", className = "techassist.service.DenyRequest")
    @ResponseWrapper(localName = "denyRequestResponse", targetNamespace = "http://techassist/", className = "techassist.service.DenyRequestResponse")
    @Action(input = "http://techassist/TechAssistServer/denyRequestRequest", output = "http://techassist/TechAssistServer/denyRequestResponse")
    public void denyRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "confirmRequest", targetNamespace = "http://techassist/", className = "techassist.service.ConfirmRequest")
    @ResponseWrapper(localName = "confirmRequestResponse", targetNamespace = "http://techassist/", className = "techassist.service.ConfirmRequestResponse")
    @Action(input = "http://techassist/TechAssistServer/confirmRequestRequest", output = "http://techassist/TechAssistServer/confirmRequestResponse")
    public void confirmRequest(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
