
package techsupport.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TechSupportServerService", targetNamespace = "http://techsupport/", wsdlLocation = "http://localhost:8888/support?wsdl")
public class TechSupportServerService
    extends Service
{

    private final static URL TECHSUPPORTSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException TECHSUPPORTSERVERSERVICE_EXCEPTION;
    private final static QName TECHSUPPORTSERVERSERVICE_QNAME = new QName("http://techsupport/", "TechSupportServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/support?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TECHSUPPORTSERVERSERVICE_WSDL_LOCATION = url;
        TECHSUPPORTSERVERSERVICE_EXCEPTION = e;
    }

    public TechSupportServerService() {
        super(__getWsdlLocation(), TECHSUPPORTSERVERSERVICE_QNAME);
    }

    public TechSupportServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TECHSUPPORTSERVERSERVICE_QNAME, features);
    }

    public TechSupportServerService(URL wsdlLocation) {
        super(wsdlLocation, TECHSUPPORTSERVERSERVICE_QNAME);
    }

    public TechSupportServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TECHSUPPORTSERVERSERVICE_QNAME, features);
    }

    public TechSupportServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TechSupportServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TechSupportServer
     */
    @WebEndpoint(name = "TechSupportServerPort")
    public TechSupportServer getTechSupportServerPort() {
        return super.getPort(new QName("http://techsupport/", "TechSupportServerPort"), TechSupportServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TechSupportServer
     */
    @WebEndpoint(name = "TechSupportServerPort")
    public TechSupportServer getTechSupportServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://techsupport/", "TechSupportServerPort"), TechSupportServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TECHSUPPORTSERVERSERVICE_EXCEPTION!= null) {
            throw TECHSUPPORTSERVERSERVICE_EXCEPTION;
        }
        return TECHSUPPORTSERVERSERVICE_WSDL_LOCATION;
    }

}
