
package techsupport.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TechSupportServer", targetNamespace = "http://techsupport/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TechSupportServer {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRequests", targetNamespace = "http://techsupport/", className = "techsupport.service.GetRequests")
    @ResponseWrapper(localName = "getRequestsResponse", targetNamespace = "http://techsupport/", className = "techsupport.service.GetRequestsResponse")
    @Action(input = "http://techsupport/TechSupportServer/getRequestsRequest", output = "http://techsupport/TechSupportServer/getRequestsResponse")
    public String getRequests();

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://techsupport/", className = "techsupport.service.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://techsupport/", className = "techsupport.service.GetStatusResponse")
    @Action(input = "http://techsupport/TechSupportServer/getStatusRequest", output = "http://techsupport/TechSupportServer/getStatusResponse")
    public int getStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "requestCreate", targetNamespace = "http://techsupport/", className = "techsupport.service.RequestCreate")
    @ResponseWrapper(localName = "requestCreateResponse", targetNamespace = "http://techsupport/", className = "techsupport.service.RequestCreateResponse")
    @Action(input = "http://techsupport/TechSupportServer/requestCreateRequest", output = "http://techsupport/TechSupportServer/requestCreateResponse")
    public int requestCreate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "requestFinish", targetNamespace = "http://techsupport/", className = "techsupport.service.RequestFinish")
    @ResponseWrapper(localName = "requestFinishResponse", targetNamespace = "http://techsupport/", className = "techsupport.service.RequestFinishResponse")
    @Action(input = "http://techsupport/TechSupportServer/requestFinishRequest", output = "http://techsupport/TechSupportServer/requestFinishResponse")
    public void requestFinish(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "requestDeny", targetNamespace = "http://techsupport/", className = "techsupport.service.RequestDeny")
    @ResponseWrapper(localName = "requestDenyResponse", targetNamespace = "http://techsupport/", className = "techsupport.service.RequestDenyResponse")
    @Action(input = "http://techsupport/TechSupportServer/requestDenyRequest", output = "http://techsupport/TechSupportServer/requestDenyResponse")
    public void requestDeny(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "requestStart", targetNamespace = "http://techsupport/", className = "techsupport.service.RequestStart")
    @ResponseWrapper(localName = "requestStartResponse", targetNamespace = "http://techsupport/", className = "techsupport.service.RequestStartResponse")
    @Action(input = "http://techsupport/TechSupportServer/requestStartRequest", output = "http://techsupport/TechSupportServer/requestStartResponse")
    public void requestStart(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "requestConfirm", targetNamespace = "http://techsupport/", className = "techsupport.service.RequestConfirm")
    @ResponseWrapper(localName = "requestConfirmResponse", targetNamespace = "http://techsupport/", className = "techsupport.service.RequestConfirmResponse")
    @Action(input = "http://techsupport/TechSupportServer/requestConfirmRequest", output = "http://techsupport/TechSupportServer/requestConfirmResponse")
    public void requestConfirm(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
