
package techsupport.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Server", targetNamespace = "http://techsupport/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Server {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStatus", targetNamespace = "http://techsupport/", className = "techsupport.service.GetStatus")
    @ResponseWrapper(localName = "getStatusResponse", targetNamespace = "http://techsupport/", className = "techsupport.service.GetStatusResponse")
    @Action(input = "http://techsupport/Server/getStatusRequest", output = "http://techsupport/Server/getStatusResponse")
    public String getStatus(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "confirmTask", targetNamespace = "http://techsupport/", className = "techsupport.service.ConfirmTask")
    @ResponseWrapper(localName = "confirmTaskResponse", targetNamespace = "http://techsupport/", className = "techsupport.service.ConfirmTaskResponse")
    @Action(input = "http://techsupport/Server/confirmTaskRequest", output = "http://techsupport/Server/confirmTaskResponse")
    public void confirmTask(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @return
     *     returns java.util.List<techsupport.service.Task>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllTasks", targetNamespace = "http://techsupport/", className = "techsupport.service.GetAllTasks")
    @ResponseWrapper(localName = "getAllTasksResponse", targetNamespace = "http://techsupport/", className = "techsupport.service.GetAllTasksResponse")
    @Action(input = "http://techsupport/Server/getAllTasksRequest", output = "http://techsupport/Server/getAllTasksResponse")
    public List<Task> getAllTasks();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "redoTask", targetNamespace = "http://techsupport/", className = "techsupport.service.RedoTask")
    @ResponseWrapper(localName = "redoTaskResponse", targetNamespace = "http://techsupport/", className = "techsupport.service.RedoTaskResponse")
    @Action(input = "http://techsupport/Server/redoTaskRequest", output = "http://techsupport/Server/redoTaskResponse")
    public void redoTask(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "finishTask", targetNamespace = "http://techsupport/", className = "techsupport.service.FinishTask")
    @ResponseWrapper(localName = "finishTaskResponse", targetNamespace = "http://techsupport/", className = "techsupport.service.FinishTaskResponse")
    @Action(input = "http://techsupport/Server/finishTaskRequest", output = "http://techsupport/Server/finishTaskResponse")
    public void finishTask(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "startTask", targetNamespace = "http://techsupport/", className = "techsupport.service.StartTask")
    @ResponseWrapper(localName = "startTaskResponse", targetNamespace = "http://techsupport/", className = "techsupport.service.StartTaskResponse")
    @Action(input = "http://techsupport/Server/startTaskRequest", output = "http://techsupport/Server/startTaskResponse")
    public void startTask(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createTask", targetNamespace = "http://techsupport/", className = "techsupport.service.CreateTask")
    @ResponseWrapper(localName = "createTaskResponse", targetNamespace = "http://techsupport/", className = "techsupport.service.CreateTaskResponse")
    @Action(input = "http://techsupport/Server/createTaskRequest", output = "http://techsupport/Server/createTaskResponse")
    public Integer createTask(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
