
package publiclibrary.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PublicLibraryServer", targetNamespace = "http://publiclibrary/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PublicLibraryServer {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addCount", targetNamespace = "http://publiclibrary/", className = "publiclibrary.service.AddCount")
    @ResponseWrapper(localName = "addCountResponse", targetNamespace = "http://publiclibrary/", className = "publiclibrary.service.AddCountResponse")
    @Action(input = "http://publiclibrary/PublicLibraryServer/addCountRequest", output = "http://publiclibrary/PublicLibraryServer/addCountResponse")
    public void addCount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @return
     *     returns java.util.List<publiclibrary.service.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllBooks", targetNamespace = "http://publiclibrary/", className = "publiclibrary.service.GetAllBooks")
    @ResponseWrapper(localName = "getAllBooksResponse", targetNamespace = "http://publiclibrary/", className = "publiclibrary.service.GetAllBooksResponse")
    @Action(input = "http://publiclibrary/PublicLibraryServer/getAllBooksRequest", output = "http://publiclibrary/PublicLibraryServer/getAllBooksResponse")
    public List<Book> getAllBooks();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "returnCount", targetNamespace = "http://publiclibrary/", className = "publiclibrary.service.ReturnCount")
    @ResponseWrapper(localName = "returnCountResponse", targetNamespace = "http://publiclibrary/", className = "publiclibrary.service.ReturnCountResponse")
    @Action(input = "http://publiclibrary/PublicLibraryServer/returnCountRequest", output = "http://publiclibrary/PublicLibraryServer/returnCountResponse")
    public void returnCount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "rentCount", targetNamespace = "http://publiclibrary/", className = "publiclibrary.service.RentCount")
    @ResponseWrapper(localName = "rentCountResponse", targetNamespace = "http://publiclibrary/", className = "publiclibrary.service.RentCountResponse")
    @Action(input = "http://publiclibrary/PublicLibraryServer/rentCountRequest", output = "http://publiclibrary/PublicLibraryServer/rentCountResponse")
    public String rentCount(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg4
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addBook", targetNamespace = "http://publiclibrary/", className = "publiclibrary.service.AddBook")
    @ResponseWrapper(localName = "addBookResponse", targetNamespace = "http://publiclibrary/", className = "publiclibrary.service.AddBookResponse")
    @Action(input = "http://publiclibrary/PublicLibraryServer/addBookRequest", output = "http://publiclibrary/PublicLibraryServer/addBookResponse")
    public void addBook(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4);

}
