
package publiclibrary.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PublicLibraryServerService", targetNamespace = "http://publiclibrary/", wsdlLocation = "http://localhost:8000/PublicLibrary?wsdl")
public class PublicLibraryServerService
    extends Service
{

    private final static URL PUBLICLIBRARYSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException PUBLICLIBRARYSERVERSERVICE_EXCEPTION;
    private final static QName PUBLICLIBRARYSERVERSERVICE_QNAME = new QName("http://publiclibrary/", "PublicLibraryServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8000/PublicLibrary?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PUBLICLIBRARYSERVERSERVICE_WSDL_LOCATION = url;
        PUBLICLIBRARYSERVERSERVICE_EXCEPTION = e;
    }

    public PublicLibraryServerService() {
        super(__getWsdlLocation(), PUBLICLIBRARYSERVERSERVICE_QNAME);
    }

    public PublicLibraryServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PUBLICLIBRARYSERVERSERVICE_QNAME, features);
    }

    public PublicLibraryServerService(URL wsdlLocation) {
        super(wsdlLocation, PUBLICLIBRARYSERVERSERVICE_QNAME);
    }

    public PublicLibraryServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PUBLICLIBRARYSERVERSERVICE_QNAME, features);
    }

    public PublicLibraryServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PublicLibraryServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PublicLibraryServer
     */
    @WebEndpoint(name = "PublicLibraryServerPort")
    public PublicLibraryServer getPublicLibraryServerPort() {
        return super.getPort(new QName("http://publiclibrary/", "PublicLibraryServerPort"), PublicLibraryServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PublicLibraryServer
     */
    @WebEndpoint(name = "PublicLibraryServerPort")
    public PublicLibraryServer getPublicLibraryServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://publiclibrary/", "PublicLibraryServerPort"), PublicLibraryServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PUBLICLIBRARYSERVERSERVICE_EXCEPTION!= null) {
            throw PUBLICLIBRARYSERVERSERVICE_EXCEPTION;
        }
        return PUBLICLIBRARYSERVERSERVICE_WSDL_LOCATION;
    }

}
