
package pizza.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PizzaServerService", targetNamespace = "http://server.pizza/", wsdlLocation = "http://localhost:8000/Pizza?wsdl")
public class PizzaServerService
    extends Service
{

    private final static URL PIZZASERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException PIZZASERVERSERVICE_EXCEPTION;
    private final static QName PIZZASERVERSERVICE_QNAME = new QName("http://server.pizza/", "PizzaServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8000/Pizza?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PIZZASERVERSERVICE_WSDL_LOCATION = url;
        PIZZASERVERSERVICE_EXCEPTION = e;
    }

    public PizzaServerService() {
        super(__getWsdlLocation(), PIZZASERVERSERVICE_QNAME);
    }

    public PizzaServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PIZZASERVERSERVICE_QNAME, features);
    }

    public PizzaServerService(URL wsdlLocation) {
        super(wsdlLocation, PIZZASERVERSERVICE_QNAME);
    }

    public PizzaServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PIZZASERVERSERVICE_QNAME, features);
    }

    public PizzaServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PizzaServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PizzaServer
     */
    @WebEndpoint(name = "PizzaServerPort")
    public PizzaServer getPizzaServerPort() {
        return super.getPort(new QName("http://server.pizza/", "PizzaServerPort"), PizzaServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PizzaServer
     */
    @WebEndpoint(name = "PizzaServerPort")
    public PizzaServer getPizzaServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.pizza/", "PizzaServerPort"), PizzaServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PIZZASERVERSERVICE_EXCEPTION!= null) {
            throw PIZZASERVERSERVICE_EXCEPTION;
        }
        return PIZZASERVERSERVICE_WSDL_LOCATION;
    }

}
