
package car.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CarServer", targetNamespace = "http://car/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CarServer {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAllCars", targetNamespace = "http://car/", className = "car.service.GetAllCars")
    @ResponseWrapper(localName = "getAllCarsResponse", targetNamespace = "http://car/", className = "car.service.GetAllCarsResponse")
    @Action(input = "http://car/CarServer/getAllCarsRequest", output = "http://car/CarServer/getAllCarsResponse")
    public String getAllCars();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "returnCar", targetNamespace = "http://car/", className = "car.service.ReturnCar")
    @ResponseWrapper(localName = "returnCarResponse", targetNamespace = "http://car/", className = "car.service.ReturnCarResponse")
    @Action(input = "http://car/CarServer/returnCarRequest", output = "http://car/CarServer/returnCarResponse")
    public void returnCar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getByModel", targetNamespace = "http://car/", className = "car.service.GetByModel")
    @ResponseWrapper(localName = "getByModelResponse", targetNamespace = "http://car/", className = "car.service.GetByModelResponse")
    @Action(input = "http://car/CarServer/getByModelRequest", output = "http://car/CarServer/getByModelResponse")
    public String getByModel(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "changeCar", targetNamespace = "http://car/", className = "car.service.ChangeCar")
    @ResponseWrapper(localName = "changeCarResponse", targetNamespace = "http://car/", className = "car.service.ChangeCarResponse")
    @Action(input = "http://car/CarServer/changeCarRequest", output = "http://car/CarServer/changeCarResponse")
    public void changeCar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addCar", targetNamespace = "http://car/", className = "car.service.AddCar")
    @ResponseWrapper(localName = "addCarResponse", targetNamespace = "http://car/", className = "car.service.AddCarResponse")
    @Action(input = "http://car/CarServer/addCarRequest", output = "http://car/CarServer/addCarResponse")
    public int addCar(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "orderCar", targetNamespace = "http://car/", className = "car.service.OrderCar")
    @ResponseWrapper(localName = "orderCarResponse", targetNamespace = "http://car/", className = "car.service.OrderCarResponse")
    @Action(input = "http://car/CarServer/orderCarRequest", output = "http://car/CarServer/orderCarResponse")
    public int orderCar(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
