
package car.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CarServerService", targetNamespace = "http://car/", wsdlLocation = "http://localhost:8080/car?wsdl")
public class CarServerService
    extends Service
{

    private final static URL CARSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException CARSERVERSERVICE_EXCEPTION;
    private final static QName CARSERVERSERVICE_QNAME = new QName("http://car/", "CarServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/car?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARSERVERSERVICE_WSDL_LOCATION = url;
        CARSERVERSERVICE_EXCEPTION = e;
    }

    public CarServerService() {
        super(__getWsdlLocation(), CARSERVERSERVICE_QNAME);
    }

    public CarServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARSERVERSERVICE_QNAME, features);
    }

    public CarServerService(URL wsdlLocation) {
        super(wsdlLocation, CARSERVERSERVICE_QNAME);
    }

    public CarServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARSERVERSERVICE_QNAME, features);
    }

    public CarServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CarServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CarServer
     */
    @WebEndpoint(name = "CarServerPort")
    public CarServer getCarServerPort() {
        return super.getPort(new QName("http://car/", "CarServerPort"), CarServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CarServer
     */
    @WebEndpoint(name = "CarServerPort")
    public CarServer getCarServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://car/", "CarServerPort"), CarServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CARSERVERSERVICE_EXCEPTION!= null) {
            throw CARSERVERSERVICE_EXCEPTION;
        }
        return CARSERVERSERVICE_WSDL_LOCATION;
    }

}
