
package hairsalon.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "HairSalonServerService", targetNamespace = "http://hairsalon/", wsdlLocation = "http://localhost:8888/hairsalon?wsdl")
public class HairSalonServerService
    extends Service
{

    private final static URL HAIRSALONSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException HAIRSALONSERVERSERVICE_EXCEPTION;
    private final static QName HAIRSALONSERVERSERVICE_QNAME = new QName("http://hairsalon/", "HairSalonServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8888/hairsalon?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HAIRSALONSERVERSERVICE_WSDL_LOCATION = url;
        HAIRSALONSERVERSERVICE_EXCEPTION = e;
    }

    public HairSalonServerService() {
        super(__getWsdlLocation(), HAIRSALONSERVERSERVICE_QNAME);
    }

    public HairSalonServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), HAIRSALONSERVERSERVICE_QNAME, features);
    }

    public HairSalonServerService(URL wsdlLocation) {
        super(wsdlLocation, HAIRSALONSERVERSERVICE_QNAME);
    }

    public HairSalonServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HAIRSALONSERVERSERVICE_QNAME, features);
    }

    public HairSalonServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HairSalonServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns HairSalonServer
     */
    @WebEndpoint(name = "HairSalonServerPort")
    public HairSalonServer getHairSalonServerPort() {
        return super.getPort(new QName("http://hairsalon/", "HairSalonServerPort"), HairSalonServer.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HairSalonServer
     */
    @WebEndpoint(name = "HairSalonServerPort")
    public HairSalonServer getHairSalonServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://hairsalon/", "HairSalonServerPort"), HairSalonServer.class, features);
    }

    private static URL __getWsdlLocation() {
        if (HAIRSALONSERVERSERVICE_EXCEPTION!= null) {
            throw HAIRSALONSERVERSERVICE_EXCEPTION;
        }
        return HAIRSALONSERVERSERVICE_WSDL_LOCATION;
    }

}
