
package hairsalon.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "HairSalonServer", targetNamespace = "http://hairsalon/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface HairSalonServer {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removeService", targetNamespace = "http://hairsalon/", className = "hairsalon.service.RemoveService")
    @ResponseWrapper(localName = "removeServiceResponse", targetNamespace = "http://hairsalon/", className = "hairsalon.service.RemoveServiceResponse")
    @Action(input = "http://hairsalon/HairSalonServer/removeServiceRequest", output = "http://hairsalon/HairSalonServer/removeServiceResponse")
    public int removeService(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getServices", targetNamespace = "http://hairsalon/", className = "hairsalon.service.GetServices")
    @ResponseWrapper(localName = "getServicesResponse", targetNamespace = "http://hairsalon/", className = "hairsalon.service.GetServicesResponse")
    @Action(input = "http://hairsalon/HairSalonServer/getServicesRequest", output = "http://hairsalon/HairSalonServer/getServicesResponse")
    public String getServices();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "removeAppointment", targetNamespace = "http://hairsalon/", className = "hairsalon.service.RemoveAppointment")
    @ResponseWrapper(localName = "removeAppointmentResponse", targetNamespace = "http://hairsalon/", className = "hairsalon.service.RemoveAppointmentResponse")
    @Action(input = "http://hairsalon/HairSalonServer/removeAppointmentRequest", output = "http://hairsalon/HairSalonServer/removeAppointmentResponse")
    public void removeAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getFreeTime", targetNamespace = "http://hairsalon/", className = "hairsalon.service.GetFreeTime")
    @ResponseWrapper(localName = "getFreeTimeResponse", targetNamespace = "http://hairsalon/", className = "hairsalon.service.GetFreeTimeResponse")
    @Action(input = "http://hairsalon/HairSalonServer/getFreeTimeRequest", output = "http://hairsalon/HairSalonServer/getFreeTimeResponse")
    public String getFreeTime(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "makeAppointment", targetNamespace = "http://hairsalon/", className = "hairsalon.service.MakeAppointment")
    @ResponseWrapper(localName = "makeAppointmentResponse", targetNamespace = "http://hairsalon/", className = "hairsalon.service.MakeAppointmentResponse")
    @Action(input = "http://hairsalon/HairSalonServer/makeAppointmentRequest", output = "http://hairsalon/HairSalonServer/makeAppointmentResponse")
    public String makeAppointment(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        int arg3);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addService", targetNamespace = "http://hairsalon/", className = "hairsalon.service.AddService")
    @ResponseWrapper(localName = "addServiceResponse", targetNamespace = "http://hairsalon/", className = "hairsalon.service.AddServiceResponse")
    @Action(input = "http://hairsalon/HairSalonServer/addServiceRequest", output = "http://hairsalon/HairSalonServer/addServiceResponse")
    public int addService(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
